---

- name: Delete the kind cluster
  command: kind delete cluster 
  
- name: Load kind config file
  become: false
  ansible.builtin.copy:
    src: "{{ kind_config_file }}" 
    dest: "{{ kind_config_file }}" 
    mode: '0664'


- name: Setup the kind cluster
  command: kind create cluster --config "{{ kind_config_file }}" 

- name: Download "{{ pod_network_name }}" pod network
  become: false
  ansible.builtin.get_url:
    url: "{{ pod_network_raw }}"
    dest: ~/kube-flannel.yml
    mode: '0664'

- name: Install "{{ pod_network_name }}" pod network
  become: false
  community.kubernetes.k8s:
    state: present
    src: ~/kube-flannel.yml

- name: Download metallb namespace yaml file
  become: false
  ansible.builtin.get_url:
    url: "{{ metallb_namespace_yaml_raw }}"
    dest: ~/metallb-namespace.yaml
    mode: '0664'

- name: Create metallb namespace
  become: false
  community.kubernetes.k8s:
    state: present
    src: ~/metallb-namespace.yaml

- name: Create the member list secrets
  become: false
  command: kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)" 

- name: Download metallb manifests yaml file
  become: false
  ansible.builtin.get_url:
    url: "{{ metallb_manifests_yaml_raw }}"
    dest: ~/metallb-manifests.yaml
    mode: '0664'


- name: Apply metallb mainifest
  become: false
  community.kubernetes.k8s:
    state: present
    src: ~/metallb-manifests.yaml

- name: Wait all pods in metallb system namespace still running
  become: false
  community.kubernetes.k8s_info:
    kind: Pod
    namespace: metallb-system
    wait_condition:
      type: Ready
      status: 'True'

- name: Setup address pool used by loadbalancers
  become: false
  shell: echo "- $( docker network inspect -f \'\{\{\.IPAM.Config\}\}\' kind | sed 's/[^0-9]*//'  | awk '{print $1}' | sed 's/\.0/\.255/' | sed 's/\.0/\.200/' | sed 's/\/.*//g' )-$( docker network inspect -f \'\{\{\.IPAM.Config\}\}\'  kind | sed 's/[^0-9]*//'  | awk '{print $1}' | sed 's/\.0/\.255/' | sed 's/\.0/\.250/' | sed 's/\/.*//g' )"
  register: ipPool

- name: Aplly ipPoolAdress in metallb configmap
  become: false
  community.kubernetes.k8s:
    state: present
    definition: 
      apiVersion: v1
      kind: ConfigMap
      metadata:
        namespace: metallb-system
        name: config
      data:
        config: |
          address-pools:
          - name: default
            protocol: layer2
            addresses:
              "{{ ipPool.stdout_lines}}"
