---
- name: Delete the kind cluster
  
  command: kind delete cluster 
  
- name: Load kind config file
  
  ansible.builtin.copy:
    src: "{{ kind_config_file }}" 
    dest: "~/{{ kind_config_file }}" 
    mode: '0664'


- name: Setup the kind cluster
  
  command: kind create cluster --config "~/{{ kind_config_file }}" 

  #- name: Download "{{ pod_network_name }}" pod network
  #  
  #  ansible.builtin.get_url:
  #    url: "{{ pod_network_raw }}"
  #    dest: "~/kube-{{ pod_network_name }}.yml"
  #    mode: '0664'
  #
  #- name: Install "{{ pod_network_name }}" pod network
  #  
  #  community.kubernetes.k8s:
  #    state: present
  #    src: "~/kube-{{ pod_network_name }}.yml"
