
- name: Setup the kind cluster
  become: false
  command: kind create cluster --config "{{ kind_config }}"

- name: Install "{{ pod_network_name }}" pod network
  become: false
  command: kubectl apply -f "{{ pod_network_raw }}"

- name: Create metallb namespace
  command: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/master/manifests/namespace.yaml

- name: Create the member list secrets
  command: kubectl create secret generic -n metallb-system memberlist --from-literal=secretkey="$(openssl rand -base64 128)" 

- name: Apply mettallb mainifest
  become: false
  command: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/master/manifests/metallb.yaml

- name: Copy the metallb configmap into the host
  copy:
    src: metllb-configmap.yaml
    dest: "{{ metallb_configmap_dest }}"

- name: Apply mettallb mainifest
  command: kubectl apply -f https://raw.githubusercontent.com/metallb/metallb/master/manifests/metallb.yaml
- name: Wait all pods in metallb system namespace still running
  community.kubernetes.k8s_info:
    kind: Pod
    namespace: metallb-system
    wait_condition:
      type: Ready
      status: True
- name: Setup address pool used by loadbalancers
  command: echo "      - $( docker network inspect -f '{{.IPAM.Config}}' kind | sed 's/[^0-9]*//'  | awk '{print $1}' | sed 's/\.0/\.255/' | sed 's/\.0/\.200/' | sed 's/\/.*//g' )-$( docker network inspect -f '{{.IPAM.Config}}' kind | sed 's/[^0-9]*//'  | awk '{print $1}' | sed 's/\.0/\.255/' | sed 's/\.0/\.250/' | sed 's/\/.*//g' ) >> {{ metallb_configmap_dest }}"
