---
- name: Add metallb repository
  community.kubernetes.helm_repository:
    name: bitnami
    repo_url: https://charts.bitnami.com/bitnami
- name: Deploy metallb
  community.kubernetes.helm_repository:
    name: metallb
    chart_ref: bitnami/metallb
