---
- name: Node Configuration
  hosts: master,workers
  roles:
  - dockerInstall 
  - apacheAb
  - stressNgInstall
  - kubernetesInstall
  - helmInstall
- name: Master Setup
  hosts: master
  roles:
  - kubeadmSetup
  - metricsServer
  - nginxIngress
- name: Kubeconfig setup
  hosts: master
  roles:
  - kubeconfigSetup
- name: Workwr Configuration
  hosts: workers
  roles:
  - dockerInstall 
  - kubernetesInstall
- name: Node Configuration
  hosts: master,workers
  roles:
  - joinNode
