---
- name: Node Configuration
  become: yes
  hosts: server
  roles:
  - dockerInstall 
  - kindInstall
  - apacheAb
  - stressNgInstall
  - kubectlInstall
  - clusterConfigure
  - helmInstall
  - metallbSetup
  - chartsInstall
