---
- name: Node Configuration
  become: yes
  hosts: 192.168.0.15
  roles:
    #    - dockerInstall 
    #    - kindInstall
    - jenkinsInstall
      #    - kubectlInstall
      #    - clusterConfigure

