---
- name: Node Configuration
  hosts: master
  roles:
  - dockerInstall 
  - apacheAb
  - stressNgInstall
  - kubernetesInstall
  - helmInstall
  - kubeadmSetup
  - metallbSetup
  - nginxIngress
  - metricsServer
  - chartsInstall

- name: Kubeconfig setup
  hosts: local
  roles:
  - kubeconfigSetup
