---
- name: Node Configuration
  become: yes
  hosts: localhost
  roles:
    #    - dockerInstall 
    #    - kindInstall
    - jenkinsInstall
      #    - kubectlInstall
      #    - clusterConfigure

