---
- name: Node Configuration
  become: yes
  hosts: server
  roles:
  - dockerInstall 
  - kindInstall
  - jenkinsInstall
  - kubectlInstall
  - clusterConfigure
  - helmInstall
  - metallbSetup
  - kubernetes

