---
- name: Node Configuration
  hosts: master
  roles:
    #- dockerInstall 
    #- apacheAb
    #- stressNgInstall
    #- kubernetesInstall
    #- helmInstall
    #- kubeadmSetup
    #- metallbSetup
    #- metricsServer
  - nginxIngress
  - chartsInstall
