---
- name: Node Configuration
  hosts: server
  roles:
  - dockerInstall 
  - apacheAb
  - stressNgInstall
  - kubernetesInstall
  - helmInstall
  - kubeadmSetup
  - metallbSetup
  - nginxIngress
  - chartsInstall

