- name: get ip addr
  shell: hostname -I | awk '{ print $1 }' 
  register: ipAddr


- name: Test apache bench performance
  shell: "time ab -n 1000000 -c 7 http://{{ ipAddr.stdout }}/"
  register: results

- name: Print return information from the previous task
  ansible.builtin.debug:
    var: result
    verbosity: 2

    #  shell: |
    #docker exec kind-worker apt update && apt install stress-ng && stress-ng --cpu 4 -l 100 --vm 1 --hdd 1 --fork 1000 --switch 1 --timeout 90s --metrics & docker exec kind-worker2 apt update && apt install stress-ng && stress-ng --cpu 4 -l 100 --vm 1 --hdd 1 --fork 1000 --switch 1 --timeout 90s --metrics
