- name: Copy StressNgScript
  ansible.builtin.copy:
    src: stressNgTestsResult
    dest: ~/stressNgTestsResult

- name: Copy StressNgScript
  ansible.builtin.copy:
    src: installStressNgInsideDocker.sh 
    dest: ~/installStressNgInsideDocker.sh 

    Test apache bench performance
  shell: |
    ab -n 1000000 -c 1000 0.0.0.0:80
    #  shell: |
    #docker exec kind-worker apt update && apt install stress-ng && stress-ng --cpu 4 -l 100 --vm 1 --hdd 1 --fork 1000 --switch 1 --timeout 90s --metrics & docker exec kind-worker2 apt update && apt install stress-ng && stress-ng --cpu 4 -l 100 --vm 1 --hdd 1 --fork 1000 --switch 1 --timeout 90s --metrics
