---
- name: Download helm-chart
  ansible.builtin.copy:
    src: ipNginxDocker/
    dest: ~/ipNginxDocker
    mode: '0664'

- name: Docker build ipnginx image
  become: yes
  shell: "docker build -t ipnginx ~/ipNginxDocker"

- name: Helm install podIpTester
  shell: "helm install podiptester ~/ipNginxDocker/kubernetes-helm-chart/ipnginx-chart"

