
- name: Create a volume to storage the jenkins datda
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: jenkins-pv
        namespace: jenkins
      spec:
        capacity: 
          storage: 2Gi
        accessModes:
          - ReadWriteOnce
        persistentVolumeReclaimPolicy: Retain
        hostPath:
          path: /opt/jenkins

- name: Create a volume to storage the jenkins datda
  community.kubernetes.k8s:
    state: present
    definition:
      kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: jenkins-pvc
        namespace: jenkins
      spec:
        storageClassName: ""
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 2Gi


- name: Create a ClusterRoleBinding to allow helm install chrats inside the cluster
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: rbac.authorization.k8s.io/v1
      kind: ClusterRoleBinding
      metadata:
        name: jenkins-rbac
      subjects:
        - kind: ServiceAccount
          name: default
          namespace: jenkins
roleRef:
  kind: ClusterRole
  name: cluster-admin
  apiGroup: rbac.authorization.k8s.io

- name: Add jenkins chart repo
  community.kubernetes.helm_repository:
    name: jenkins
    repo_url: "https://charts.jenkins.io "

- name: Deploy latest version of jenkins chart inside monitoring namespace with values
  community.kubernetes.helm:
    name: jenkins
    chart_ref: jenkins/jenkins
    release_namespace: jenkins
    create_namespace: true
    values:
      controller:
        adminUser: "admin"
        adminPassword: "admin"
        serviceType: NodePort
        nodePort: 32323
      backup:
        runAsUser: 0
        fsGroup: 0
      persistence:
        existingClaim: jenkins-pvc
        storageClass: "-"

