apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ .Release.Name }}-php-configmap
data:
  APP_NAME: 'Laravel'
  APP_ENV: 'local'
  APP_KEY: 'base64:QoRtp35GTwqLimd4hbq2Jlh59w9ui+SbEPK7Q3RN7DY='
  APP_DEBUG: 'true'
  APP_URL: 'http://127.0.0.1'
  LOG_CHANNEL: 'stack'
  LOG_LEVEL: 'debug'
  DB_CONNECTION: 'mysql'
  DB_HOST: '127.0.0.1'
  DB_PORT: '3306'
  DB_DATABASE: 'exercicio'
  DB_USERNAME: 'root'
  DB_PASSWORD: '12341234'
  BROADCAST_DRIVER: 'log'
  CACHE_DRIVER: 'file'
  QUEUE_CONNECTION: 'sync'
  SESSION_DRIVER: 'file'
  SESSION_LIFETIME: '120'
  MEMCACHED_HOST: '127.0.0.1'
  MIX_PUSHER_APP_KEY: "${PUSHER_APP_KEY}"
  MIX_PUSHER_APP_CLUSTER: "${PUSHER_APP_CLUSTER}"

