apiVersion: v1
kind: Secret
metadata:
  name: {{ .Release.Name }}-auth
data:
  DB_ENV_PORT: {{ default ""  .Values.port | b64enc | quote }}
  DB_ENV_DATABASE: {{ default ""  .Values.database | b64enc | quote }}
  DB_ENV_USERNAME: {{ default ""  .Values.username | b64enc | quote }}
  DB_ENV_PASSWORD: {{ default ""  .Values.password | b64enc | quote }}
