- name: get Cloudflare API zone_id 
  uri:
    url: https://www.mms.microsoft.com/Embedded/Api/ConfigDataSources/LogManagementData/Save
    method: GET
    body_format: json
    status_code: [200, 202]
    return_content: true
    headers:
      Content-Type: application/json
      x-ms-client-workspace-path: /subscriptions/{{ sub_id }}/resourcegroups/{{ res_group }}/providers/microsoft.operationalinsights/workspaces/{{ w_spaces }}
      x-ms-client-platform: ibiza
      x-ms-client-auth-token: "{{ token_az }}"

- name: Connect to CloudFlare API using acess token
  uri:
    url: https://api.cloudflare.com/client/v4/zones/
    method: GET
    return_content: yes
    headers:
      X-Auth-Email: "XXXXXXXXXXXXXX" 
      X-Auth-Key: "XXXXXXXXXXXXXXXXXXXXXX" 
      Content-Type: "application/json"
  register: result
  until: result.status == 200
  retries: 10
  delay: 30

- name: "Display all server ports and names from cluster1"
  set_fact:
    'name_{{ item.name }}': '{{ item.port }}'
  with_items: "{{ result['result'] | json_query(server_querry) }}"
  vars:
    server_query: {{ result['result'] | json_query(query) }}

- name: Connect to CloudFlare API using acess token
  vars:
    query: {{ result['result'] | json_query(query) }}
  uri:
    url: "https://api.cloudflare.com/client/v4/zones/"
    method: GET
    return_content: yes
    headers:
      X-Auth-Email: "XXXXXXXXXXXXXX" 
      X-Auth-Key: "XXXXXXXXXXXXXXXXXXXXXX" 
      Content-Type: "application/json"
  register: result
  until: result.status == 200
  retries: 10
  delay: 30


