- name: Connect to CloudFlare API using acess token
  uri:
    url: https://api.cloudflare.com/client/v4/zones/
    method: GET
    return_content: yes
    headers:
      X-Auth-Email: "gcftutos@gmail.com" 
      X-Auth-Key: "538fca28d9038dd14b85d95c22c9f71926b2c" 
      Content-Type: "application/json"
  register: result
  until: result.status == 200
  retries: 10
  delay: 30
- debug:
    msg: "{{ result.json['result'] }}"
- name: "Display all server ports and names from cluster1"
  set_fact:
    zoneNameIdassociate: "'{{ item.name }}': '{{ item.id }}'"
  with_items: "{{ result.json['result'] | json_query(server_query) }}"
  vars:
    server_query: "[].{name: name, id: id}"

- name: Connect to CloudFlare API using acess token
  vars:
    query:  "[? name==`fitfatfix.com`].{id}"
  uri:
    url: "https://api.cloudflare.com/client/v4/zones/{{ item }}"
    with_items: "{{ zoneNameIdassociate }}" 
    method: GET
    return_content: yes
    headers:
      X-Auth-Email: "gcftutos@gmail.com" 
      X-Auth-Key: "538fca28d9038dd14b85d95c22c9f71926b2c" 
      Content-Type: "application/json"
  register: result
  until: result.status == 200
  retries: 10
  delay: 30


