- name: swapoff
  shell: swapoff -a
- name: Init the kubernetes cluster 
  shell: "kubeadm init --pod-network-cidr {{ pod_network_cidir }}"
- name: export KUBECONFIG
  shell: |
    mkdir -p $HOME/.kube
    sudo cp -f /etc/kubernetes/admin.conf $HOME/.kube/config
    sudo chown $(id -u):$(id -g) $HOME/.kube/config

- name: Untaint the kubernetes cluster 
  shell: kubectl taint nodes --all node-role.kubernetes.io/master-

- name: Deploy flannel pod network chart
  shell: kubectl apply -f https://raw.githubusercontent.com/coreos/flannel/master/Documentation/kube-flannel.yml
