  
- name: Create mysql volume
  community.kubernetes.k8s:
    state: present
    definition:
      apiVersion: v1
      kind: PersistentVolume
      metadata:
        name: mysql-pv
      spec:
        capacity: 
          storage: 2Gi
        accessModes:
          - ReadWriteOnce
          - ReadOnlyMany
        persistentVolumeReclaimPolicy: Retain
        hostPath:
          path: /opt/mysql


- name: Create mysql volume claim
  community.kubernetes.k8s:
    state: present
    definition:
      kind: PersistentVolumeClaim
      apiVersion: v1
      metadata:
        name: mysql-pvc
        namespace: default
      spec:
        storageClassName: ""
        accessModes:
          - ReadWriteOnce
        resources:
          requests:
            storage: 1Gi
