- name: Get your own ip address
  shell: hostname -I | awk '{ print $1 }'
  register: ipAddr
- name: Copy nginx-inhgress deploy file with owner and permissions
  ansible.builtin.copy:
    src: deploy.yaml 
    dest: ~/nginx-deploy.yaml
    mode: '0644'
- name: Replace EXTERNAL_IP with the server ip
  replace:
    path: ~/nginx-deploy.yaml
    regexp: 'EXTERNAL_IP'
    replace: "{{ ipAddr.stdout }}"
- name: Apply nginx ingress manifests
  shell: kubectl apply -f ~/nginx-deploy.yaml
  #  community.kubernetes.k8s:
  #      state: present
  #      src: ~/nginx-deploy.yaml
# From repository

#- name: Add nginx-ingress namespace
#  community.kubernetes:
#    state: present
#    definition:
#      apiVersion: v1
#      kind: Namespace
#      metadata:
#        name: ingress-nginx
#        labels:
#          app.kubernetes.io/name: ingress-nginx
#          app.kubernetes.io/instance: ingress-nginx
#- name: Add stable chart repo
#  community.kubernetes.helm_repository:
#    name: stable
#    repo_url: "https://kubernetes.github.io/ingress-nginx"
# 
#- name: Deploy nginx-ingress chart 
#  community.kubernetes.helm:
#    name: nginxIngress
#    chart_ref: https://raw.githubusercontent.com/kubernetes/ingress-nginx/controller-v0.46.0/deploy/static/provider/baremetal/deploy.yaml
#    release_namespace: ingress-nginx
#    
